repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff linter
        entry: pdm run ruff check
        language: system
        types_or: [python, pyi, jupyter]
        args: [--fix, --select=I]
      - id: ruff-format
        name: ruff formatter
        entry: pdm run ruff
        language: system
        types_or: [python, pyi, jupyter]
  - repo: local
    hooks:
      - id: mypy
        name: mypy type checker
        entry: pdm run mypy
        language: system
        types: [python]
